tiki/apps-receipt-capacitor

src/components/tiki/Tiki.vue, src/components/tiki/element/HistoryDetails.vue, src/components/tiki/screen/History.vue, src/components/tiki/screen/Reward.vue
=> feat: add history screen

example/src/assets/learn-more.md, example/src/assets/terms.md, example/src/main.ts, src/components/learn-sheet.vue, src/components/terms-sheet.vue
Adds a default templated terms of service and learn more page.
closes #30 
closes #29
=> fix: Default terms and learn more page

.github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/version.yaml, .gitignore, README.md, example/package-lock.json, example/package.json, package-lock.json, package.json, src/main.ts, src/service/config.ts, src/service/history/history-event.ts, src/service/history/history-service.ts, src/service/receipt/receipt-account-type.ts, src/service/receipt/receipt-account.ts, src/service/receipt/receipt-event.ts, src/service/receipt/receipt-service.ts, src/service/sdk-service.ts, src/service/tiki-service.ts, src/tiki-receipt.vue, src/vite-env.d.ts
Initial release -not complete. Validating release process and docs.
=> Release: add docs

package.json
=> fix: version bump to force redeploy

.github/workflows/release.yml, package-lock.json, package.json
=> fix: typedoc

example/capacitor.config.ts, example/package-lock.json, example/package.json, package-lock.json, package.json, src/service/receipt/receipt-service.ts, src/service/sdk-service.ts
=> feat: send receipts to ingest service

src/service/receipt/receipt-account-type.ts, src/service/receipt/receipt-account.ts
changed the services receipt-account-type and receipt-account.
the enum turned into a static class, clean the methods as they are not going to be used in the actual design.
also changed the receipt account to receive the account type in the right way.
now gonna refactor all the code that uses both services.
Closes #100
=> fix: turn the enum into a static class of providers.

src/components/account/account-form.vue, src/components/account/account-item.vue, src/components/account/account-link.vue, src/components/account/account-unlink.vue, src/main.ts, src/service/receipt/receipt-account.ts, src/service/receipt/receipt-service.ts, src/service/tiki-service.ts
refactor of the login and logout methods
deleted the calls for flush, removeEmail and removeRetailer methods
=> refactor: refactoring the login and logout method

README.md, package.json
=> Updates for changing orgs

README.md, example/android/build.gradle, example/package-lock.json, example/package.json, package-lock.json, package.json
=> fix: update to capture 0.3.1

example/ios/App/Podfile, example/ios/App/Podfile.lock, example/package-lock.json, example/package.json, package-lock.json
close #187
Updates the capture-capacitor to 0.5.0 due to wrong PR merge.
=> fix: update capture receipt version

src/service/receipt/receipt-service.ts
Closes #195 
Fixed the verification in the scan method, that will be works to scan the account after the login method
=> fix: fix scan call after the login method

src/components/account/account-link.vue, src/components/account/account-unlink.vue, src/components/buttons/text-button.vue, src/components/reward/reward-action.vue
None.
Removes icons from the text-button component. The design no longer uses them. This is simply a cleanup as they were previously optional.
=> fix: remove icons from text button

src/components/account/account-list.vue, src/components/account/account-status.vue
resolves #205
emits delete with the account to be deleted.
=> fix: adds account list component

example/package-lock.json, src/components/sheet/sheet-add-retailer.vue
Closes #258
just added the login method in the form submit
=> fix: login retailer in add retailer sheet

src/assets/md/learn-more.md, src/components/sheet/sheet-learn.vue
Closes #219.
- Updates copy and layout for the Learn More screen
- Enables support for HTML (and other options) in the Markdown parser for the Learn More sheet
---
https://github.com/tiki/apps-receipt-capacitor/assets/671968/6d798b4c-a902-4c06-83aa-9321e65f74fd
=> Update copy and layout for the Learn More screen

src/components/sheet/sheet-home.vue, src/service/publish/index.ts, src/service/tiki/index.ts, src/service/tiki/internal-handlers.ts, src/tiki-receipt.vue
closes #256 
Balance works. Payout works, but should be rigorously tested.
=> fix: add payout on criteria met.

example/ios/App/Podfile.lock, example/package-lock.json, example/package.json, package-lock.json, package.json, src/service/publish/index.ts
=> Release: pilot

src/service/capture/index.ts, src/service/publish/index.ts, src/service/store/repository.ts
=> fix: filter out erroneous receipts

src/components/sheet/sheet-add-retailer.vue
Closes #300 
I've just deleted the other email providers as it was with gmail
=> fix: email providers removed from the dropdown

src/tiki-receipt.vue
=> fix: popup animation

vue2/package.json, vue3/package.json
resolves https://github.com/tiki/apps/issues/12
=> fix: version bump

README.md, example/vue2/src/main.ts, example/vue3/src/main.ts, src/config/index.ts, src/options/index.ts, vue3/main.ts
=> fix: make withdrawl optional

README.md, vue2/package.json, vue3/package.json
resolves https://github.com/tiki/apps/issues/13
=> release: 0.5.2

src/components/sheet/sheet-bottom.vue, src/tiki-receipt.vue
=> fix: background overlay fade in

README.md, example/vue2/ios/App/App.xcodeproj/project.pbxproj, example/vue2/ios/App/Podfile, example/vue2/ios/App/Podfile.lock, example/vue2/package-lock.json, example/vue2/package.json, example/vue3/ios/App/Podfile, example/vue3/package.json, makefile, vue2/package.json, vue3/package.json
=> fix: bump tikisdk 3.0.0

src/components/account/account-status.vue, src/components/button/button-icon.vue, src/components/sheet/sheet-learn.vue
resolves #321
Changing the class names solved this issue. But we should use BEM or OOCSS to avoid this kind of error.
=> fix: close and learn btn align

src/components/CLO/clo-card-offer.vue, src/components/header/header-title.vue
=> fix: offer sheet pixel perfect

README.md, vue2/package.json, vue3/package.json
=> Release 0.5.4

example/vue2/ios/App/App.xcodeproj/project.pbxproj, example/vue2/package-lock.json, example/vue2/src/main.ts, example/vue3/package-lock.json, src/components/sheet/sheet-home.vue, src/config/index.ts, src/options/index.ts, src/service/publish/index.ts, vue2/package.json
Close #425
Not sure if we need to call the callback after the publish method be successful or during the Capture scan receipt flow, I've choose the first approach
=> Add optional on receipt callback
